let num1: number = 20;
let num2: number = 10;
let addition: number = num1 + num2;
let subtraction: number = num1 - num2;
let multiplication: number = num1 * num2;
let division: number = num1 / num2;
console.log("Addition:", addition);
console.log("Subtraction:", subtraction);
console.log("Multiplication:", multiplication);
console.log("Division:", division);